sonar.projectKey=ENI-ECOLE-INFORMATIQUE_RCDA014_QCDA011_Devops_TPFILRouge
sonar.organization=eni-ecole-informatique


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=RCDA014_QCDA011_Devops_TPFILRouge
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
